# Generated by Django 3.1.3 on 2020-11-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('authors', models.CharField(max_length=50)),
                ('publishedDate', models.DateField()),
                ('isbn_type', models.CharField(max_length=7)),
                ('isbn_id', models.CharField(max_length=13)),
                ('pageCount', models.IntegerField()),
                ('image', models.URLField()),
                ('language', models.CharField(max_length=50)),
            ],
        ),
    ]
