# Generated by Django 3.1.3 on 2020-11-02 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn_id',
            new_name='isbnId',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='isbn_type',
            new_name='isbnType',
        ),
    ]
