# Generated by Django 3.1.3 on 2020-11-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookManagement', '0002_auto_20201102_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pageCount',
            field=models.PositiveIntegerField(),
        ),
    ]
