# Generated by Django 3.1.3 on 2020-11-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookManagement', '0003_auto_20201102_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbnId',
            field=models.CharField(help_text='Insert ISBN ID compatible with type you have chosen. For example (for ISBN-13): 978-2-1234-5680-3 or 9782123456803.', max_length=17),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbnType',
            field=models.CharField(choices=[('ISBN-10', 'ISBN-10'), ('ISBN-13', 'ISBN-13')], help_text='Choose type of ISBN normalization you want to use.', max_length=7),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishedDate',
            field=models.DateField(help_text="Use 'yyyy-mm-dd' date format. For example '2020-10-30'."),
        ),
    ]
