# Generated by Django 3.1.3 on 2020-11-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookManagement', '0004_auto_20201103_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbnId',
            field=models.CharField(help_text='\n                                            Insert ISBN ID compatible with type you have chosen. \n                                            For example (for ISBN-13): 978-2-1234-5680-3 or 9782123456803.")\n                                          ', max_length=17, unique=True),
        ),
    ]
